### ISSUE TITLE
大哥NB

### ISSUE THREAD

**Issue by kinglyl** [365cent/365#1]
大哥NB，能教我`php-proxy-app`的插件怎么用么，我下载`YoutubePlugin`到`plugins`文件夹后，代理就炸了

**Comment by 365cent** [comment]
插件在vendor/athlon1600/php-proxy-plugin-bundle/src目录下，而且自带就有，无需手动添加

**Comment by kinglyl** [comment]
请问如何把`url_form.php`中的那个地址栏弄出来，我尝试复制了css但并不行。。
