### ISSUE TITLE
Pornhub 插件爆炸

### ISSUE THREAD

**Issue by kinglyl** [365cent/365#2]
大佬如何修复的Pornhub插件，它又炸了。

**Comment by kinglyl** [comment]
大佬，我修复Pornhub插件了，私聊一下我给你发。

**Comment by 365cent** [comment]
缩略图问题修复了吗？

**Comment by kinglyl** [comment]
> 缩略图问题修复了吗？

我这边基本除了搜索不行，其他都正常了，大佬看看

https://52proxy.fun

**Comment by kinglyl** [comment]
大佬，要不要我把插件发你，你带我make money ? 😜

**Comment by 365cent** [comment]
我这也没啥可赚钱的项目，你先发呗
